{{- range $componentIndex, $component := .Values.components }}
{{- range $portMapIndex, $portMapUnused := $component.service.ports }}
{{- if eq $portMapIndex 0 }}
apiVersion: v1
kind: Service
metadata:
  {{- if $component.service.name }}
  name: {{ $component.service.name | quote }}
  {{- else }}
  name: {{ $component.name | quote }}
  {{- end }}
  labels:
    "app.kubernetes.io/name": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
spec:
  ports:
    {{- range $portMapIndex, $portMap := $component.service.ports }}
    - name: "port-{{ $portMapIndex }}"
      port: {{ $portMap.externalPort }}
      targetPort: {{ $portMap.containerPort }}
      protocol: {{ $portMap.protocol | default "TCP" | quote }}
    {{- end }}
  selector:
    "app.kubernetes.io/name": {{ $.Release.Name | quote }}
    "app.kubernetes.io/component": {{ $component.name | quote }}
  type: {{ $component.service.type | default "ClusterIP" | quote }}
---
{{- end }}
{{- end }}
{{- end }}
