cluster:
  kubeContext: ""
  namespace: hello-world
deployments:
- helm:
    chartPath: ./chart
  name: devspace-app
dev:
  autoReload:
    deployments:
    - devspace-app
  overrideImages:
  - entrypoint:
    - sleep
    - "999999999999"
    name: default
  ports:
  - portMappings:
    - localPort: 3000
      remotePort: 3000
    selector: default
  selectors:
  - labelSelector:
      app.kubernetes.io/component: default
      app.kubernetes.io/name: devspace-app
    name: default
  sync:
  - containerPath: /app
    localSubPath: ./
    selector: default
images:
  default:
    build:
      context: .
      dockerfile: Dockerfile
    createPullSecret: true
    image: smartpcr/devspace
version: v1alpha3
